library(raster)
OldN<-read.table("C:/Users/hac809/Documents/Pughtam-cropozone/Global_evaluation_inputs/nfert2.dat",h=T)
AgN<-read.table("C:/Users/hac809/Desktop/newcrops_sensitivity_old/data/env/Nfertalter1.dat",h=T)
NewN<-read.table("C:/Users/hac809/Desktop/newcrops_sensitivity_old/data/env/NfertN.dat",h=T)
NewN_<-subset(NewN,Year==2000)
OldN_<-subset(OldN,Year==2000)
AgNr<-rasterFromXYZ(AgN[,c(1:3)])
OldNr<-rasterFromXYZ(OldN_[,c(1,2,6)])
NewNr<-rasterFromXYZ(NewN_[,c(1,2,6)])
x11()
plot(AgNr,zlim=c(0,0.05),main="AgN")
plot(OldNr,zlim=c(0,0.05),main="OldN")
plot(NewNr,zlim=c(0,0.05),main="NewN")
plot(NewNr-AgNr,zlim=c(-0.05,0),main="NewN-AgN")
plot(OldNr-AgNr,zlim=c(-0.05,0.02),main="OldN-AgN")
plot(OldNr,xlim=c(0,50),ylim=c(0,50), main="OldN_zoom")
plot(OldNr,xlim=c(80,120),ylim=c(10,50), main="OldN_zoom2")
